# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/4/16 15:28
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
import turtle
import time

turtle.color("red")
turtle.goto(0, 0)

turtle.forward(100)
turtle.right(144)
turtle.forward(100)
turtle.right(144)
turtle.forward(100)
turtle.right(144)
turtle.forward(100)
turtle.right(144)
turtle.forward(100)
turtle.goto(144, 0)

turtle.write("Welcome to Python")
time.sleep(3)
