# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/4/25 22:43
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
def test_case2_01(open_51):
    print("51job，列出所有职位用例")


def test_case2_02(open_51):
    print("51job，找出所有python岗位")
