# -*- coding: utf-8 -*-

# @Time:2022/2/13
#@version:
# Created by: Python3.9.6
#@author:鹄思鹄想bit森
# WARNING: run again.  Do not edit this file unless you know what you are doing.
'''
20220213csdn3给一个链表的头节点head和一个整数val,删除链表所有满足node.val==val的节点。
'''
