# -*- coding: utf-8 -*-

# @Time:2021/10/06
#@version:
# Created by: Python3.9.6
#@author:鹄思鹄想bit森
# WARNING: run again.  Do not edit this file unless you know what you are doing.
# 杭州五彩云面试题，应该基础掌握requests最基本爬虫知识
# 写一个简易的爬虫.
# 1.抓起百度首页保存到文件baidu_index.html中.
# 2.进一步解析该文件中所有超链接输出到文件baidu_link中,超链接用","分隔