# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/4/24 21:36
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
import pytest


@pytest.fixture(scope="function", params=None, autouse=False,
                ids=None, name=None)
def test():
    print("fixture初始化的参数列表")
