# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/4/16 23:31
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
import pytest


def setup_module():
    print("=====整个.py模块开始前只执行一次:打开浏览器=====")


def teardown_module():
    print("=====整个.py模块结束后只执行一次:关闭浏览器=====")


def setup_function():
    print("===每个函数级别用例开始前都执行setup_function===")


def teardown_function():
    print("===每个函数级别用例结束后都执行teardown_function====")


def test_one():
    print("one")


def test_two():
    print("two")


def setup_class():
    print("====整个测试类开始前只执行一次setup_class====")


def teardown_class():
    print("====整个测试类结束后只执行一次teardown_class====")


def teardown_method():
    print("==类里面每个用例结束后都会执行teardown_method==")


def setup_method():
    print("==类里面每个用例执行前都会执行setup_method==")


def teardown():
    print("=类里面每个用例结束后都会执行teardown=")


def setup():
    print("=类里面每个用例执行前都会执行setup=")


class TestCase:

    def test_three(self):
        print("three")

    def test_four(self):
        print("four")


if __name__ == '__main__':
    pytest.main(["-q", "-s", "-ra", "module.py"])
