# -*- coding: utf-8 -*-
# @Time:2022/3/13
# @version:
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.  Do not edit this file unless you know what you are doing.

def func(x):
    return x+1


def test_answer():
    assert func(4) == 5
