# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/4/17 18:11
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
import pytest


@pytest.mark.parametrize("user,psw",
                         [("lsl1", "123456"),
                          ("lsl2", "123456"),
                          ("lsl3", "123456")])
def test_login(user, psw):
    print(user + " : " + psw)
    assert 1 == 1
