# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/4/16 23:20
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
import pytest
# 详细断言异常


@pytest.mark.xfail(raises=ZeroDivisionError)
def test_f():
    1 / 0


def test_zero_division_long():
    with pytest.raises(ZeroDivisionError) as excinfo:
        1 / 0

    # 断言异常类型 type
    assert excinfo.type == ZeroDivisionError
    # 断言异常 value 值
    assert "division by zero" in str(excinfo.value)
