# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/4/20 11:07
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 输入某年某月某日，判断这一天是这一年的第几天
import datetime


def day_of_year():
    year = int(input("请输入年份："))
    month = int(input("请输入月份："))
    day = int(input("请输入天："))
    date1 = datetime.date(year=int(year), month=int(month), day=int(day))
    date2 = datetime.date(year=int(year), month=1, day=1)
    return (date1 - date2).days+1


if __name__ == "__main__":
    print(day_of_year())
    pass
