# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/6/17 10:27
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.


a = 3
print(2 < a < 8)  # True
print(1 == a < 2)  # False
if __name__ == "__main__":
    pass
