# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/6/17 10:39
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 以下代码段可将字符串列表转换为单个字符串，列表中的每个元素用逗号分隔。

hobbies = ["basketball", "football", "swimming"]
print("My hobbies are: " + ", ".join(
    hobbies))  # My hobbies are: basketball, football, swimming
if __name__ == "__main__":
    pass
