# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/6/17 10:54
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
import re


def count_vowels(str):


    return len(len(re.findall(r'[aeiou]', str, re.IGNORECASE)))
count_vowels('foobar')  # 3
count_vowels('gym')  # 0
