# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/6/17 10:54
# @version: 1.0.2
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 以下方法可计算字符串中元音字母（‘a’, ‘e’, ‘i’, ‘o’, ‘u’）的数目。
import re


def count_vowels(str):
    return len(len(re.findall(r'[aeiou]', str, re.IGNORECASE)))


count_vowels('foobar')  # 3
count_vowels('gym')  # 0
if __name__ == "__main__":
    pass
