# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/6/18 12:30
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
def decapitalize(string):
    return str[:1].lower() + str[1:]


decapitalize('FooBar')  # 'fooBar'
decapitalize('FooBar')  # 'fooBar'
