# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/6/18 12:30
# @version: 1.0.2
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 以下方法可用于将给定字符串的第一个字母转换为小写。

def decapitalize(string):
    return str[:1].lower() + str[1:]


decapitalize('FooBar')  # 'fooBar'
decapitalize('FooBar')  # 'fooBar'
if __name__ == "__main__":
    pass
