# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/6/18 12:43
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
def difference(a, b):
    set_a = set(a)
    set_b = set(b)
    comparison = set_a.difference(set_b)
    return list(comparison)
    difference([1, 2, 3], [1, 2, 4])  # [3]
