# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/6/18 18:36
# @version: 1.0.2
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 下面的方法在将给定的函数应用于两个列表的每个元素后，返回两个列表之间的差值。
from math import floor


def difference_by(a, b, fn):
    b = set(map(fn, b))

    return [item for item in a if fn(item) not in b]


difference_by([2.1, 1.2], [2.3, 3.4], floor)  # [1.2]
difference_by([{'x': 2}, {'x': 1}], [{'x': 1}],
              lambda v: v['x'])  # [ { x: 2 } ]

if __name__ == "__main__":
    pass
