# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/7/2 22:09
# @version: 1.0.2
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 以下方法可用于合并两个词典。

def merge_two_dicts(a, b):
    c = a.copy()  # make a copy of a
    c.update(b)  # modify keys and values of a with the ones from b
    return c


a = {'x': 1, 'y': 2}
b = {'y': 3, 'z': 4}
print(merge_two_dicts(a, b))  # {'y': 3, 'x': 1, 'z': 4}
if __name__ == "__main__":
    pass
