# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/7/5 21:56
# @version: 1.0.2
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 以下方法可将两个列表转换成一个词典。
def to_dictionary(keys, values):
    return dict(zip(keys, values))


keys = ["a", "b", "c"]
values = [2, 3, 4]
print(to_dictionary(keys, values))  # {'a': 2, 'c': 4, 'b': 3}
if __name__ == "__main__":
    pass
