# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/7/6 11:07
# @version: 1.0.2
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 你可以将 else 子句作为 try/except 块的一部分，如果没有抛出异常，则执行该子句。

try:
    2 * 3
except TypeError:
    print("An exception was raised")
else:
    print("Thank God, no exceptions were raised.")
# Thank God, no exceptions were raised.
if __name__ == "__main__":
    pass
