# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/7/6 15:54
# @version: 1.0.2
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 以下方法可检查给定的字符串是否为回文结构。该方法首先将字符串转换为小写，然后从中删除非字母数字字符。最后，它会将新的字符串与反转版本进行比较。
def palindrome(string):
    from re import sub

    s = sub('[\W_]', '', string.lower())
    return s == s[::-1]


palindrome('taco cat')  # True
if __name__ == "__main__":
    pass
