# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/7/6 21:02
# @version: 1.0.2
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 以下方法可使列表扁平化，类似于JavaScript中的[].concat(…arr)。
def spread(arg):
    ret = []
    for i in arg:
        if isinstance(i, list):
            ret.extend(i)
        else:
            ret.append(i)
    return ret


spread([1, 2, 3, [4, 5, 6], [7], 8, 9])  # [1,2,3,4,5,6,7,8,9]
if __name__ == "__main__":
    pass
