# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/7/6 21:05
# @version: 1.0.2
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 以下是交换两个变量的快速方法，而且无需使用额外的变量。

def swap(a, b):
    return b, a
    a, b = -1, 14

    swap(a, b)  # (14, -1)


if __name__ == "__main__":
    pass
