# -*- coding: utf-8 -*-

# @Time:2022/0/
#@version:
# Created by: Python3.9.6
#@author:鹄思鹄想bit森
# WARNING: run again.  Do not edit this file unless you know what you are doing.
# 代码片实例中使用，检测
from collections import counter

def anagram(first,second):
    '''
    
    :param first: 字符串1
    :param second: 字符串2
    :return: 
    '''
    return counter(first)==counter(second)
anagram("abc3","3abc")