# -*- coding: utf-8 -*-

# @Time:2022/1/17
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again. Do not edit this file unless you know what you are doing.
# 代码片实例中使用，检测回文
from collections import Counter


def anagram(first, second):

    return Counter(first) == Counter(second)


anagram("cba3", "3abc")

if __name__ == "__main__":
    pass
