# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/7/6 21:08
# @version: 1.0.2
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 以下代码段显示了如何在字典中没有包含要查找的键的情况下获得默认值。

d = {'a': 1, 'b': 2}
print(d.get('c', 3))  # 3
if __name__ == "__main__":
    pass
