# -*- coding: utf-8 -*-

# @Time:2022/4/19
# @version: 1.0.2
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.
# Do not edit this file unless you know what you are doing.
# 检查内存使用情况
import sys

variable = 3
print(sys.getsizeof(variable))
if __name__ == "__main__":
    pass
