# -*- coding: utf-8 -*-

# @Time:2022/0/
# @version: 1.01
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.
# Do not edit this file unless you know what you are doing.
# 重复打印字符串
n = 5
s = 'pro'
print(s * n)

if __name__ == "__main__":
    pass
