# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/6/11 23:38
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
s = "programming is awesome"
print(s.title())

if __name__ == "__main__":
    pass
