# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/6/11 23:38
# @version: 1.0.2
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 以下代码段使用 title() 方法将字符串内的每个词进行首字母大写。
s = "programming is awesome"
print(s.title())

if __name__ == "__main__":
    pass
