# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/6/16 23:53
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.


from math import ceil


def chunk(lst, size):
    return list(
        map(lambda x: lst[x * size:x * size + size],
            list(range(0, ceil(len(lst) / size)))))


chunk([1, 2, 3, 4, 5], 2)  # [[1,2],[3,4],5]
