# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/6/13 22:41
# @version: 1.0.2
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 以下方法使用 fliter() 删除列表中的错误值（如：False, None, 0 和“”）

def compact(lst):
    return list(filter(bool, lst))


compact([0, 1, False, 2, '', 3, 'a', 's', 34])  # [ 1, 2, 3, 'a', 's', 34 ]
if __name__ == "__main__":
    pass
