# -*- coding: utf-8 -*-
# @Time:2022/01/23
#@version:
# Created by: Python3.9.6
#@author:鹄思鹄想bit森
# WARNING: run again.  Do not edit this file unless you know what you are doing.编程语法总结
#以下为fb编程案例内容，很久没进行总结，需要即时基础翻阅，基础查阅即可，去注释，可以不去注释
# import requests
# from aip import AipOcr
#
# image = requests.get('https://static.pandateacher.com/7b5d6d8d9dea5691705d04fef2306b52.png').content
#
# APP_ID = '16149264'
# API_KEY = 'yxYg9r4OuAs4fYvfcl8tqCYd'
# SECRET_KEY = 'yWg3KMds2muFsWs7MBSSFcgMQl8Wng4s'
#
# client = AipOcr(APP_ID, API_KEY, SECRET_KEY)
# res = client.basicGeneral(image)
# if 'words_result' in res.keys():
#     for item in res['words_result']:
#         print(item['words'])
# else:
#     print(res)
import  this
print(this)
'''
1.基础print()函数输出 
基本换行案例
'''
#双引号是函数结构，单引号属于字符串内容
print("jason在'hony'里拿了奖章。")
'''
字符串内容用到转义符需正确使用函数结构体三引号，以下为错误，被注释，在下面为正确
'''
# print('把我的幻影和梦\n
# 放在狭长的贝壳里\n
# 柳枝编成的船篷\n
# 还旋绕着夏蝉的长鸣\n
# 拉紧桅绳\n
# 风吹起晨雾的帆\n
# 我开航了')
print('''把我的幻影和梦
放在狭长的贝壳里\n
柳枝编成的船篷\n
还旋绕着夏蝉的长鸣\n
拉紧桅绳\n
风吹起晨雾的帆\n
我开航了\n''')
#练习打印图型
# 除了文字和数字之外，我们还可以灵活运用print()函数，打印出带特殊格式的东西，例如：字符画。现在，请试着打印出一只属于自己的“皮卡丘”
print('''    へ　　　　　／|
　　/＼7　　　 ∠＿/
　 /　│　　 ／　／
　│　Z ＿,＜　／　　 /`ヽ
　│　　　　　ヽ　　 /　　〉
　 Y　　　　　`　 /　　/
　ｲ●　､　●　　⊂⊃〈　　/
　()　 へ　　　　|　＼〈
　　>ｰ ､_　 ィ　 │ ／／
　 / へ　　 /　ﾉ＜| ＼＼
　 ヽ_ﾉ　　(_／　 │／／
　　7　　　　　　　|／
　　＞―r￣￣`ｰ―＿''')
'''
变量赋值
'''
a = 2#声明，赋值
a==2#比较运算符，等于的意义
#遍历取前不取后
'''
不同于while循环，元组，列表，字典，集合，字符串都可以是“一群排队办业务的人”。
'''
for i in  [6,1,8]:
    print(i)
for i in  (1,5,9):
    print(i)
for i in range(6):
    print(i)
for i in "hook":
    print(i)
for i in {1,2,3}:
    print(i)
for i in {'boot':0,'br-lunch':'chicken'}:
    print(i)
#1.遍历range
# for i in range(10):
#     print(i)
for i in range(10,1,-2):#以二等差递减遍历10到1
    if i%4==0:continue#去除4的倍数
    print(i,end=",")#i结尾为逗号