# -*- coding: utf-8 -*-
# @Time:2022/01/22
#@version:
# Created by: Python3.9.6
#@author:鹄思鹄想bit森
# WARNING: run again.  Do not edit this file unless you know what you are doing.编程语法总结
#以下为fb编程案例内容，很久没进行总结，需要即时基础翻阅，基础查阅即可，去注释，可以不去注释

'''
1.基础print()函数输出 
基本换行案例
'''
#练习打印图型
# 除了文字和数字之外，我们还可以灵活运用print()函数，打印出带特殊格式的东西，例如：字符画。现在，请试着打印出一只属于自己的“皮卡丘”
print('''    へ　　　　　／|
　　/＼7　　　 ∠＿/
　 /　│　　 ／　／
　│　Z ＿,＜　／　　 /`ヽ
　│　　　　　ヽ　　 /　　〉
　 Y　　　　　`　 /　　/
　ｲ●　､　●　　⊂⊃〈　　/
　()　 へ　　　　|　＼〈
　　>ｰ ､_　 ィ　 │ ／／
　 / へ　　 /　ﾉ＜| ＼＼
　 ヽ_ﾉ　　(_／　 │／／
　　7　　　　　　　|／
　　＞―r￣￣`ｰ―＿''')