# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/4/17 12:20
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 给定一个 没有重复 数字的序列，返回其所有可能的全排列。
#
# 示例:
#
# 输入: [1,2,3]
# 输出:[  [1,2,3],  [1,3,2],  [2,1,3],  [2,3,1],  [3,1,2],  [3,2,1]]
class Solution:
    def permute(self, nums):
        e = []
        if (len(nums) == 1):
            return [nums]
        for i in range(len(nums)):
            q = self.permute(nums[:i] + nums[i + 1:])
            for c in q:
                e.append([nums[i]] + c)
        return e


# %%
s = Solution()
print(s.permute(nums=[1, 2, 3]))

if __name__ == "__main__":
    pass
