# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/4/19 22:30
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 如果用户选择菜单选项1，提示用户输入1到10之间的整数，并打印一个乘法表，显示整数1与输入整数相乘的结果，如下面的示例所示。
# 注意:不需要检查输入的数字是否在1到10之间。如果用户选择菜单选项2，退出程序。
# 如果用户在菜单选择中输入了1或2以外的任何内容，输出信息“菜单选择错误，请重试并继续程序。”
# 结果应该如下： 1)创建乘法表 2)退出程序 请从以上菜单中选择一个选项:1 输入一个介于1到10之间的整数:3
#
# 1 2 3
#
# 2 4 6
#
# 3 6 9
#
# 1)创建乘法表 2)退出程序 请从以上菜单中选择一个选项:
# 4 菜单选择错误，请重试 1)创建乘法表 2)退出程序 请从以上菜单中选择一个选项：2 谢谢你使用乘法表
# while True:
#     print('1)创建乘法表')
#     print('2)退出程序')
#     n = input('请从以上菜单中选择一个选项:').strip()
#     if n == '1':
#         x = int(input('输入一个介于1到10之间的整数:'))
#         for i in range(1, x // 1):
#             for j in range(1, x + 1):
#                 print("{:>4}".format(i * j), end="")
#             print()
#     elif n == '2':
#         print('谢谢你使用乘法表')
#         break
#     else:
#         print('菜单选择错误，请重试')
#     print('-----------------------------')

# while True:
#     print('1)创建乘法表')
#     print('2)退出程序')
#     n = input('请从以上菜单中选择一个选项:').strip()
#     if n == '1':
#         x = int(input('输入一个介于1到10之间的整数:'))
#         for i in range(1, x * 1):
#             for j in range(1, x + 1):
#                 print("{:>4}".format(i * j), end="")
#             print()
#     elif n == '2':
#         print('谢谢你使用乘法表')
#         break
#     else:
#         print('菜单选择错误，请重试')
#     print('-----------------------------')

while True:
    print('1)创建乘法表')
    print('2)退出程序')
    n = input('请从以上菜单中选择一个选项:').strip()
    if n == '1':
        x = int(input('输入一个介于1到10之间的整数:'))
        for i in range(1, x + 1):
            for j in range(1, x + 1):
                print("{:>4}".format(i * j), end="")
            print()
    elif n == '2':
        print('谢谢你使用乘法表')
        break
    else:
        print('菜单选择错误，请重试')
    print('-----------------------------')

if __name__ == "__main__":
    pass
