# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/4/24 16:36
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
class TreeNode:
    def __init__(self, x):
        self.val = x
        self.left = None
        self.right = None


class Solution:
    def minDepth(self, root: TreeNode) -> int:
        if not root:
            return 0
        queue = [root]
        count = 1
        while queue:
            next_queue = []
            for node in queue:
                if not node.left and not node.right:
                    return count
                if node.left:
                    next_queue.append(node.left)
                if node.right:
                    next_queue.append(node.right)
            queue = next_queue
            count += 1
        return count
