# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/4/25 10:45
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
def numTrees(n):
    """
    :type n: int
    :rtype: int
    """
    dp = [0] * (n + 1)
    dp[0] = 1
    dp[1] = 1
    for level in range(2, n + 1):
        for root in range(1, level + 1):
            dp[level] += dp[level - root] * dp[root - 1]
    return dp[n]


class Solution(object):
    pass


# %%
s = Solution()
print(numTrees(n=3))
