# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/4/29 15:50
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 编写Python程序实现素数处理的功能，要求如下：
#
# （1）从键盘输入一个整数X，编写一个函数Find（x=100），找出1—X之间的所有的素数（即质数），
# 并将这些素数按照升序存放在列表prime_list []中。
#
# （2）在程序中编写一个函数delete_seven(prime_list)，将prime_list []中个位含有7的素数删除；
#
# 【程序要求：】
#
# （1）有引导用户键盘输入的提示信息，言语要恰当；
#
# （2）函数Find（x=100）实现要正确，实现列表prime_list []中查询到的素数的输出；
#
# （3）函数delete_seven(prime_list)实现正确，输出删除指定素数后的相关数据信息。
def find(x=100):
    pl = []
    for m in range(2, x + 1):
        for k in pl:
            if m % k == 0:
                break
        else:
            pl.append(m)
    return pl


def delete_seven(pl):
    return [x for x in pl if x % 10 != 7]


x = int(input('输入一个整数:'))
prime_list = find(x)
print(prime_list)
print(delete_seven(prime_list))
