# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/5/4 22:56
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 任意输入一个大于10的偶数，编程找出所有和等于该偶数的素数对
#
# 以下程序实现了这一功能，请你填补空白处内容：
#
# h = 0
# def a(h):
# 	x = 0
# 	for j in range(2, h):
# 		if h % j == 0:
# 			x = 1
# 			break
# 	if x == 0:
# 		return 1
# n = int(input("输入任意大于10的偶数："))
# for i in range(n,n+1):
# 	h = 0
# 	if i % 2 == 0:
# 		for k in range(2, i):
# 			if a(k) == 1 and a(i - k) == 1:
# 				________________;
h = 0


def a(h):
    x = 0
    for j in range(2, h):
        if h % j == 0:
            x = 1
            break
    if x == 0:
        return 1


n = int(input("输入任意大于10的偶数："))
for i in range(n, n + 1):
    h = 0
    if i % 2 == 0:
        for k in range(2, i):
            if a(k) == 1 and a(i - k) == 1:
                h = 1
                if h == 0:
                    print("%d can't" % i)
                    break
                else:
                    print("%d=%d+%d" % (i, k, i - k))
                    break
