# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/5/15 12:45
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 统计所有小于非负整数n的质数的数量。
#
# 示例 1：
#
# 输入：n = 10
# 输出：4
# 解释：小于 10 的质数一共有 4 个, 它们是 2, 3, 5, 7 。
#
#
# 示例 2：
#
# 输入：n = 0
# 输出：0
#
#
# 示例 3：
#
# 输入：n = 1
# 输出：0
#
# 提示：
#
# 0 <= n <= 5 * 106
# class Solution {
#     public int countPrimes(int n) {
#         int flag = 0;
#         if (n > 2)
#             flag = 1;
#         for (int i = 0; i < n; i++) {
#             for (int j = 2; j < i; j++) {
#                 if (i % j == 0) {
#                     break;
#                 }
#                 if (j == i - 1) {
#                     flag++;
#                 }
#             }
#         }
#         return flag;
#     }
# }