# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/5/14 23:10
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 实现int sqrt(int x)函数。
#
# 计算并返回x的平方根，其中x 是非负整数。
#
# 由于返回类型是整数，结果只保留整数的部分，小数部分将被舍去。
#
# 示例 1:
#
# 输入: 4
# 输出: 2
#
# 示例 2:
#
# 输入: 8
# 输出: 2
# 说明: 8 的平方根是 2.82842..., 由于返回类型是整数，小数部分将被舍去。
class Solution:
    def mySqrt(self, x):
        if x == 0:
            return 0
        if x < 4:
            return 1
        res = 2 * self.mySqrt(x / 4)
        if x >= (res + 1) * (res + 1) >= 0:
            return res + 1
        return res


# %%
s = Solution()
print(s.mySqrt(145))
