# !usr/bin/env python
# -*- coding: utf-8 -*-
# @Time:2022/5/26 23:45
# @version: 1.0.1
# Created by: Python3.9.6
# @author:鹄思鹄想bit森
# WARNING: run again.Do not edit this file unless you know what you are doing.
# 输入一个正数n，计算出因子里面分别有几个4和7，输出因子中4和7的个位数
#
# 以下程序实现了这一功能，请你填补空白处内容：
#
# n = int(input("输入数字："))
# factor = [n]
# num = 1
# __________________;
# print(factor)
# m = [str(i) for i in factor]
# count4 = 0
# count7 = 0
# for i in m:
# 	if '4' in i:
# 		count4 += 1
# 		print('以4结尾的因子的个位数：', int(i)%10)
# 	if '7' in i:
# 		count7 += 1
# 		print('以7结尾的因子的个位数：', int(i)%10)
# print('因子里面分别有{0}个4和{1}个7'.format(count4,count7))

n = int(input("输入数字："))
factor = [n]
num = 1
while num <= n / 2 + 1:
    if n % num == 0:
        factor.append(num)
    num = num + 1
print(factor)
m = [str(i) for i in factor]
count4 = 0
count7 = 0
for i in m:
    if '4' in i:
        count4 += 1
        print('以4结尾的因子的个位数：', int(i) % 10)
    if '7' in i:
        count7 += 1
        print('以7结尾的因子的个位数：', int(i) % 10)
print('因子里面分别有{0}个4和{1}个7'.format(count4, count7))
